# fly.toml app configuration file generated for valera-web on 2023-07-22T15:13:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "valera-web"
primary_region = "lhr"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true  # optional

  [[services.ports]]
    handlers = ["tls"]
    port = "443"
    tls_options = { "alpn" = ["h2", "http/1.1"] }
    
  [services.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
  [[services.http_checks]]
    grace_period = "10s"
    interval = "5s"
    method = "GET"
    timeout = "5s"
    path = "/"

[[statics]]
    guest_path = "site/static"
    url_prefix = "/static"
    
[[statics]]
    guest_path = "site/pkg"
    url_prefix = "/pkg"

[deploy]
    strategy = "bluegreen"
